name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carbon_icons: ^0.0.1+2
  emoji_picker_flutter: ^3.0.0
  fl_chart: ^0.69.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  mockito: ^5.4.4
  mocktail: ^1.0.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1
  timezone: 0.9.4

dev_dependencies:
  build_runner: ^2.4.12
  floor_generator: ^1.5.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

targets:
  $default:
    builders:
      mockito:
        generate_for:
          - test/**/*_test.dart

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 700
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
